---

- name: Install gluster server packages
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - glusterfs-server

  # Set up LVM according to:
  # https://access.redhat.com/articles/2352211#app_lvm
- name: Create LVM partition
  parted:
    device: /dev/vdb
    label: msdos
    part_type: primary
    number: 1
    flags: [ lvm ]
    state: present

- name: Create LVM VG
  lvg:
    pvs: /dev/vdb1
    vg: vg_brick

- name: Create VG thin pool
  command: lvcreate -l 100%FREE --thinpool vg_brick/pool
  args:
    creates: /dev/mapper/vg_brick-pool

  # rpcbind will fail to start the 1st time if selinux is enforcing
  # https://bugzilla.redhat.com/show_bug.cgi?id=1474593
- name: Set permissive mode for SELinux
  selinux:
    policy: targeted
    state: permissive

- name: Start gluster server
  systemd:
    name: glusterd
    enabled: yes
    state: started

- name: Re-enable SELinux enforcing mode
  selinux:
    policy: targeted
    state: enforcing
