- name: Create mount points
  file:
    name: "/mnt/{{item}}1"
    state: directory
  with_items: '{{ansible_devices|reject("equalto", "vda")|list}}'
- name: Ensure file systems are not mounted
  mount:
    path: /mnt/{{item}}1
    state: unmounted
  with_items: '{{ansible_devices|reject("equalto", "vda")|list}}'
- name: Set up data partition
  parted:
    device: "/dev/{{item}}"
    number: 1
    state: present
  with_items: '{{ansible_devices|reject("equalto", "vda")|list}}'
- name: Format xfs file systems
  filesystem:
    fstype: xfs
    dev: /dev/{{item}}1
    opts: -i size=512
  with_items: '{{ansible_devices|reject("equalto", "vda")|list}}'
- name: Mount file systems
  mount:
    path: /mnt/{{item}}1
    src: /dev/{{item}}1
    fstype: xfs
    state: mounted
  with_items: '{{ansible_devices|reject("equalto", "vda")|list}}'
